config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'readings/create'
  root to: 'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sigunup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
    end
  end
  resources :reads 
  resources :readings
  resources :willreads
  resources :relationships, only: [:create, :destroy]
end

app/models/read.rb
class Read < ApplicationRecord
  #読んだ本に関するmodel
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }


  validates :details, presence: true

  validates :image, presence: true

  mount_uploader :image, ImageUploader #画像アップロード機能の搭載     

  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      read_tag = Tag.find_or_create_by(name: new)
      self.tags << read_tag
    end
  end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController

    before_action :require_user_logged_in

 def index
    #@reads = Read.order(id: :desc).page(params[:page]).per(25)
    @reads = current_user.reads.order(id: :desc).page(params[:page])
    @tag_list = Tag.all
 end
 
 def show
    @read = Read.find(params[:id])
    @read_tags = @read.tags
 end

 def new
    @read = Read.new
 end

 def create
   @read = current_user.reads.new(read_params)
   tag_list = params[:read][:name].split(nil)
    if @read.save
       @read.save_tag(tag_list)
        flash[:success] = '読んだ本の登録に成功しました'
        redirect_to @read
    else
        flash.now[:danger] = '読んだ本の登録に失敗しました'
        render :new
    end
 end

 def edit
   @read = Read.find(params[:id])
 end

 def update
   @read = Read.find(params[:id])
   tag_list = params[:read][:name].split(nil)
   if @read.update(read_params)
      @read.save_tag(tag_list)
      flash[:success] = '読んだ本の編集が成功しました'
      redirect_to @read
   else
      flash.now[:danger] = '読んだ本の編集が失敗しました'
      render :edit
   end
 end


 private 
 def read_params
   params. require(:read).permit(:tags, :title, :image, :details)
 end

end

app/helpers/reads_helper.rb
module ReadsHelper

end

app/views/reads/_form.html.erb
  <div class="uk-container uk-container-center">
    <div class="uk-grid-width-expand">
      <%= form_with(model: read, local: true) do |f| %>
       <%= render 'layouts/error_messages', model: f.object %>
        
        <div class="form-group">
          <%= f.label :name, "タグをつける。複数タグをつけるには','で区切ってください" %>
          <%= f.text_field :name, class: "form-control", id:'tag_ids' %>
        </div>  
       
        <div class="form-group">
          <%= f.label :title, '本のタイトル' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :details, '読んだ本の詳細' %>
          <%= f.text_area :details, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :image, '本の画像' %>
          <%= f.file_field :image, class: 'form-control' %>
        </div>

        <%= f.submit '読んだ本を登録', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>

app/views/reads/_reads.html.erb
  <% reads.each do |read| %>
    <div class="uk-child-width-1-2@m" uk-grid>
         <div>
             <div class="uk-card uk-card-default">
                 <div class="uk-card-media-top">
                     <%= image_tag read.image.url %>
                 </div>
                 <div class="uk-card-body">
                      <h3 class="uk-card-title"><%= read.title %></h3>
                      <p><%= read.details %></p>

                 </div>
                 <div class="uk-card-footer">
                      <a class="uk-button uk-button-default"><%= link_to '詳細画面へ',read_path(read.id, tag.id) %></a>
                      
                 </div>
             </div>
         </div>
     </div>    
  <% end %>  

app/views/reads/edit.html.erb
<div class= "text-center">
  <h2>読んだ本を編集する</h2>
</div>
<%= render 'reads/form', read: @read %>

app/views/reads/index.html.erb
<%= render 'reads/reads', reads: @reads, tag_list: @tag_list %>

app/views/reads/new.html.erb
<div class= "text-center">
  <h2>読んだ本を登録する</h2>
</div>

<%= render 'reads/form', read: @read %>

app/views/reads/show.html.erb
<div class="uk-child-width-1-2@m" uk-grid>
    <div>
        <div class="uk-card uk-card-default">
            <div class="uk-card-media-top">
                <%= image_tag @read.image.url %>
            </div>
            <div class="uk-card-body">
                <h3 class="uk-card-title"><%= @read.title %></h3>
                <p><%= @read.details %></p>
                     <% @read_tags.each do |tag| %>
                         <%= tag.name %>
                      <% end %>
            </div>
            <div class="uk-card-footer">
              <a class="uk-button uk-button-default"><%= link_to '読んだ本の編集',edit_read_path(@read) %></a>             
            </div>
        </div>
    </div>
</div>    