config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'readings/create'
  root to: 'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sigunup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
    end
  end
  resources :reads 
  resources :readings
  resources :willreads
  resources :relationships, only: [:create, :destroy]
end

app/models/reading.rb
class Reading < ApplicationRecord
  #読んでいる本に関するmodel
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :details, presence: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader

  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships

  def readingsave_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      reading_tag = Tag.find_or_create_by(name: new)
      self.tags << reading_tag
    end
  end  
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController

  before_action :require_user_logged_in
  
  def index 
    @readings = current_user.readings.order(id: :desc).page(params[:page])
  end

  def show
    @reading = Reading.find(params[:id])
    @reading_tags = @reading.tags
  end

  def new
    @reading = Reading.new
  end

  def create
    @reading = current_user.readings.new(reading_params)
    tag_list = params[:reading][:name].split(nil)
     if @reading.save 
       @reading.readingsave_tag(tag_list)
      flash[:success] = '読んでいる本の登録に成功しました'
      redirect_to @reading
     else
      flash[:danger]
      render :new
     end
  end

  def edit 
    @reading = Reading.find(params[:id])
    @reading_tags = @reading.tags
  end

  def update
    @reading = Reading.find(params[:id])
    tag_list = params[:reading][:name].split(nil)
    if @reading.update(reading_params) 
      @reading.readingsave_tag(tag_list)
      flash[:success] = '読んでいる本の編集に成功しました'
      redirect_to @reading
    else
      flash[:danger]
      render :new
    end
  end

  private
  def reading_params
    params. require(:reading).permit(:tags, :title, :image, :details)
  end
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/_form.html.erb
  <div class="uk-container uk-container-center">
    <div class="uk-grid-width-expand">
      <%= form_with(model: reading, local:true) do |f| %>
       <%= render 'layouts/error_messages', model: f.object %>
       
        <div class="form-group">
          <%= f.label :name, "タグをつける。複数タグをつけるには','で区切ってください" %>
          <%= f.text_field :name, class: "form-control", id:'tag_ids'%>
        </div>
        <div class="form-group">
          <%= f.label :title, '本のタイトル' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :details, '読んでいる本の詳細' %>
          <%= f.text_area :details, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :image, '本の画像' %>
          <%= f.file_field :image, class: 'form-control' %>
        </div>

        <%= f.submit '読んでいる本を登録', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>

app/views/readings/_readings.html.erb
  <% readings.each do |reading| %>
    <div class="uk-child-width-1-2@m" uk-grid>
         <div>
             <div class="uk-card uk-card-default">
                 <div class="uk-card-media-top">
                     <%= image_tag reading.image.url %>
                 </div>
                 <div class="uk-card-body">
                      <h3 class="uk-card-title"><%= reading.title %></h3>
                      <p><%= reading.details %></p>
                 </div>
                 <div clss="uk-card-footer">
                      <a class="uk-button uk-button-default"><%= link_to '詳細画面へ',reading_path(reading.id) %></a>
                      
                 </div>
             </div>
         </div>
     </div>    
  <% end %>  

app/views/readings/edit.html.erb
<div class= "text-center">
  <h2>読んでいる本の編集をする</h2>
</div>

<%= render 'readings/form', reading: @reading %>

app/views/readings/index.html.erb
<%= render 'readings/readings', readings: @readings %>

app/views/readings/new.html.erb
<div class= "text-center">
  <h2>読んでいる本を登録する</h2>
</div>

<%= render 'readingsform', reading: @reading %>

app/views/readings/show.html.erb
<div class="uk-child-width-1-2@m" uk-grid>
    <div>
        <div class="uk-card uk-card-default">
            <div class="uk-card-media-top">
                <%= image_tag @reading.image.url %>
            </div>
            <div class="uk-card-body">
                <h3 class="uk-card-title"><%= @reading.title %></h3>
                <p><%= @reading.details %></p>
                <% @reading_tags.each do |tag| %>
                  <%= tag.name %>
                <% end %>
            </div>
            <div class="uk-card-footer">
              <a class="uk-button uk-button-default"><%= link_to '読んでいる本の編集', edit_reading_path %>
            </div>
        </div>
    </div>
</div>    