config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'readings/create'
  root to: 'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sigunup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
    end
  end
  resources :reads 
  resources :readings
  resources :willreads
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    #メールを小文字にして保存⬇︎
    before_save { self.email.downcase! }
     #パスワードを二重チェックし、暗号化
    has_secure_password         

    validates :name, presence: true, length: { maximum: 50 }    #名前は50文字以下を許可
    validates :email, presence: true, length: { maximum: 255 },  #emailは255文字以下を許可
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }                  #email重複を許可せず、大文字と小文字の区別はつけない



    mount_uploader :image, ImageUploader #画像アップロード機能の搭載                  

    has_many :reads    #書籍登録の読んだ本用


    has_many :readings  #書籍登録の読んでいる本用

    has_many :willreads  #書籍登録の読みたい本用

    has_many :relationships      #フォローしているユーザーのモデル参照
    has_many :followings, through: :relationships, source: :follow
    has_many :reverses_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'  #フォローされているユーザーのモデル参照

    has_many :followers, through: :reverses_of_relationships, source: :user


    def follow(other_user)
        unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
        end
    end

    def unfollow(other_user)
        relationship = self.relationships.find_by(follow_id: other_user.id)
        relationship.destroy if relationship
    end

    def following?(other_user)
        self.followings.include?(other_user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])

    #フォローカウント用
    counts(@user)   
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save 
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end    
  end

  def followings 
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user) 
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end

  private

  def user_params
    params. require(:user).permit(:name, :email, :password, :password_confiramation, :image )
  end  

end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
  end

app/views/users/_users.html.erb
<% if users.any? %>
<ul class="uk-list">
<% users.each do |user| %>
<li class="list">
  <% if user.image? %>
     <div class="uk-card uk-card-default uk-width-1-2@m">
        <div class="uk-card-header">
            <div class="uk-grid-small uk-flex-middle" uk-grid>
                <div class="uk-width-auto">
                    <%= image_tag user.image.url, size: 100 %>
                </div>
                <div class="uk-width-expand">
                    <h3 class="uk-card-title uk-margin-remove-bottom"><%= user.name %></h3>
                    <p class="uk-text-meta uk-margin-remove-top"><time datetime="2016-04-01T19:00">April 01, 2016</time></p>
                </div>
            </div>
        </div>
        <div class="uk-card-body">
            <p>後でここにユーザの自己紹介などを追加するといいと思うがmigrationし直しが必要</p>
        </div>
        <div class="uk-card-footer">
            <%= link_to 'ユーザの詳細', user_path(user.id) %>
        </div>
    </div>
  <% else %>
       <div class="uk-card uk-card-default uk-width-1-2@m">
        <div class="uk-card-header">
            <div class="uk-grid-small uk-flex-middle" uk-grid>
                <div class="uk-width-auto">
                    <img class="uk-border-circle" width="40" height="40" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
                </div>
                <div class="uk-width-expand">
                    <h3 class="uk-card-title uk-margin-remove-bottom"><%= user.name %></h3>
                    <p class="uk-text-meta uk-margin-remove-top"><time datetime="2016-04-01T19:00">April 01, 2016</time></p>
                </div>
            </div>
        </div>
        <div class="uk-card-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
        </div>
        <div class="uk-card-footer">
            <%= link_to 'ユーザの詳細', user_path(user.id) %>
        </div>
    </div>
  <% end %>
</li>
  <% end %>
 </ul>
 <%= paginate users %>
<% end %>  

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/followers.html.erb
<h3>フォローされているユーザー</h3>
<%= render 'users', users:@followers %> 

app/views/users/followings.html.erb
<H3>フォローしているユーザー</h3>
<%= render 'users', users:@followings %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class= "text-center">
  <h2>登録する</h2>
</div>

  <div class="uk-container uk-container-center">
    <div class="uk-grid-width-expand">
      <%= form_with(model: @user, local:true) do |f| %>
       <%= render 'layouts/error_messages', model: f.object %>
       
        <div class="form-group">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email, 'Email' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password, 'Password' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, 'Confirmation' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :image, 'プロフィール画像' %>
          <%= f.file_field :image, class: 'form-control' %>
        </div>

        <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<div class="uk-card uk-card-default uk-width-1-2@m">
    <div class="uk-card-header">
        <div class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-auto">
            <% if @user.image? %>
              <%= image_tag @user.image.url, size: 200 %> 
            <% else %>
                 <img class="mr-2 rounded" src="<%= gravatar_url(@user, { size: 50 }) %>" alt="">
            <% end %>    
            </div>
            <div class="uk-width-expand">
                <h3 class="uk-card-title uk-margin-remove-bottom"><%= @user.name %></h3>
                    <ul class="nav nav-tabs nav-justified mb-3">
                       <li><%= link_to '読んだ本', reads_path %></li>
                       <li><%= link_to '読んでいる本', readings_path %></li>
                       <li><%= link_to '読みたい本', willreads_path %></li>
                       <li><%= link_to 'フォーロー', followings_user_path %></li>
                       <li><%= link_to 'フォロワー', followers_user_path %></li>
                    </ul>
                <p class="uk-text-meta uk-margin-remove-top"></p>
            </div>
            <div class="uk-width-expand">
               <p uk-margin>
                <div class="uk-inline">
                  <button class="uk-button uk-button-default" type="button">書籍登録</button>
                  <div uk-dropdown>
                     <ul class="uk-nav uk-dropdown-nav">
                       <li><%= link_to '読んだ本の登録', new_read_path %></li>
                       <li><%= link_to '読んでいる本の登録', new_reading_path %></li>
                       <li><%= link_to '読みたい本の登録', new_willread_path %></li>
                     </ul>
                  </div>
                </div>
               </p>
            </div>
        </div>
    </div>
    <div class="uk-card-body">
    <ul class="uk-list">
      <li><%= @count_followings %></li>
      <li><%= @count_followers %></li>
    </ul>

        <p>ここにユーザの自己紹介文などがあればいいのかもしれない。入れるのを検討してみよう</p>
    </div>
    <div class="uk-card-footer">
       <%= render 'relationships/follow_button', user: @user %>
    </div>

</div>