config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'readings/create'
  root to: 'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sigunup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
    end
  end
  resources :reads 
  resources :readings
  resources :willreads
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="uk-navbar-container" uk-navbar>
    <div class="uk-navbar-left">

        <ul class="uk-navbar-nav">
            <li class="uk-active"><a href="/">YourBookshelf</a></li>
            <li><a href="#">About</a></li>
              <li>
                <a href="#">User</a>
                <div class="uk-navbar-dropdown">
                    <ul class="uk-nav uk-navbar-dropdown-nav">
                       <% if logged_in? %>
                        <li><%= link_to 'プロフィール', user_path(current_user) %></li>
                        <li><%= link_to 'ユーザー一覧', users_path %></li>
                        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
                       <% else %> 
                        <li><%= link_to 'Sign up', sigunup_path, class: 'nav_link' %></li>
                        <li><%= link_to 'Login', login_path, class: 'nav_link' %></li>
                      <% end %>  
                    </ul>
                </div>
             </li>

            <li>
              <div class="uk-navbar-item">
                <form class="uk-search uk-search-default">
                   <span uk-search-icon></span>  
                   <input class="uk-search-input" type="search" placeholder="Search...">
                </form>
              </div>
            </li>
        </ul>

    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Your Bookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/css/uikit.min.css" />
    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/js/uikit-icons.min.js"></script>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if current_page?(root_path) %>
     <div class="uk-height-medium uk-flex uk-flex-center uk-flex-middle uk-background-cover uk-light" data-src="assets/toppage.jpg" uk-img>
       <h4>本を読んで繋がろう！！</h4> 
     </div>
    <% else %>      
      <%= render 'layouts/flash_messages' %>
    <% end %>
      <%= yield %>
  </body>
</html>